# Generated by Django 3.0.9 on 2020-11-16 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.TextField(blank=True, max_length=255)),
                ('avatar', models.ImageField(blank=True, default='images/avatar.png', null=True, upload_to='images/')),
                ('is_atendente', models.BooleanField(default=False, null=True)),
                ('is_restaurante', models.BooleanField(null=True)),
                ('visible', models.BooleanField(default=False, null=True)),
                ('communicate', models.BooleanField(default=False, null=True)),
                ('code', models.UUIDField(default=uuid.uuid4, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Liker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curtida', models.BooleanField(blank=True, default=False)),
                ('block', models.BooleanField(blank=True, default=False)),
                ('like_anonimo', models.BooleanField(blank=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('like_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fromuser', to=settings.AUTH_USER_MODEL)),
                ('like_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='touser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
