# Generated by Django 3.0.9 on 2020-11-18 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20201118_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='images/avatar.png', null=True, upload_to='images/'),
        ),
    ]
