# Generated by Django 3.0.9 on 2020-11-21 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantes', '0002_auto_20201121_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurante',
            name='imagem_menu',
            field=models.ImageField(blank=True, default='menu/back.jpg', null=True, upload_to='menu/'),
        ),
    ]
