# Generated by Django 3.0.9 on 2020-11-22 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantes', '0003_auto_20201121_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurante',
            name='imagem_menu',
            field=models.ImageField(blank=True, default='menu/logotipo.png', null=True, upload_to='menu/'),
        ),
    ]
