# Generated by Django 3.0.9 on 2020-11-22 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantes', '0004_auto_20201122_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurante',
            name='imagem_menu',
            field=models.ImageField(blank=True, default='menu/backgr.jpg', null=True, upload_to='menu/'),
        ),
    ]
