# Generated by Django 3.0.9 on 2020-11-23 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantes', '0005_auto_20201122_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='instrucoes_1',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='instrucoes_2',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='instrucoes_3',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='instrucoes_4',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='instrucoes_5',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
