# Generated by Django 3.0.9 on 2020-11-24 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantes', '0008_restaurante_deactivate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurante',
            name='name',
            field=models.CharField(error_messages={'blank': 'Digite um nome'}, max_length=255),
        ),
    ]
