# Generated by Django 3.0.9 on 2020-11-24 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantes', '0009_auto_20201124_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurante',
            name='name',
            field=models.CharField(error_messages={'required': 'Digite um nome'}, max_length=255),
        ),
    ]
