# Generated by Django 3.0.9 on 2020-11-25 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantes', '0010_auto_20201124_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurante',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
