# Generated by Django 3.0.9 on 2020-11-25 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantes', '0011_auto_20201125_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurante',
            name='imagem_menu',
            field=models.ImageField(blank=True, default='menu/backgr.jpg', null=True, upload_to='qr_codes'),
        ),
    ]
