# Generated by Django 3.0.9 on 2020-11-26 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantes', '0012_auto_20201125_1813'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('opened', models.BooleanField(default=False)),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurantes.Restaurante')),
            ],
        ),
    ]
