# Generated by Django 3.0.9 on 2020-12-02 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantes', '0013_opendate'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='photo10',
            field=models.ImageField(blank=True, upload_to='site_photos'),
        ),
        migrations.AddField(
            model_name='site',
            name='photo3',
            field=models.ImageField(blank=True, upload_to='site_photos'),
        ),
        migrations.AddField(
            model_name='site',
            name='photo4',
            field=models.ImageField(blank=True, upload_to='site_photos'),
        ),
        migrations.AddField(
            model_name='site',
            name='photo5',
            field=models.ImageField(blank=True, upload_to='site_photos'),
        ),
        migrations.AddField(
            model_name='site',
            name='photo6',
            field=models.ImageField(blank=True, upload_to='site_photos'),
        ),
        migrations.AddField(
            model_name='site',
            name='photo7',
            field=models.ImageField(blank=True, upload_to='site_photos'),
        ),
        migrations.AddField(
            model_name='site',
            name='photo8',
            field=models.ImageField(blank=True, upload_to='site_photos'),
        ),
        migrations.AddField(
            model_name='site',
            name='photo9',
            field=models.ImageField(blank=True, upload_to='site_photos'),
        ),
    ]
