# Generated by Django 3.0.9 on 2020-11-26 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantes', '0013_opendate'),
        ('tables', '0002_tableitens_open_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tableitens',
            name='open_date',
        ),
        migrations.AddField(
            model_name='table',
            name='open_date',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurantes.OpenDate'),
        ),
    ]
